### PR TITLE
Team 4: Feedback System, Sprint 1 (Frontend)

### PR DESCRIPTION
**Pull request by drew-harris**

### CODE REVIEW

**Comment by EthanChou1** [comment]
Feedback display
Screenshot of feedback display

**Comment by drew-harris** [comment]
image

**Comment by drew-harris** [comment]
Screenshot 2024-03-22 at 12 42 54 PM

**Comment by drew-harris** [comment]
Screenshot 2024-03-22 at 12 59 48 PM

**Comment by drewstew2021** [comment]
Screenshot 2024-03-22 at 1 00 07 PM

**Pull request merged**
